version: '3'
services:
  serverless:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    env_file:
      - .env
    container_name: serverless
    ports:
      - "5000:5000"
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    user: root
    env_file:
      - .env
    container_name: dynamo
    ports:
      - "8000:8000"
    volumes:
      - yuru-db-data:/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
  dynamodb-admin:
    container_name: test_dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local

volumes:
  yuru-db-data:
